version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 'kaxn69np2h5gt3bh'
       MYSQL_DATABASE: vc_wp_codesnippets
       MYSQL_USER: umysql_vc
       MYSQL_PASSWORD: '555gpah4jzetczpf'
     networks:
      - app-network

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
        - ./wp:/var/www/html
     ports:
       - 8000:80
       - 443:443
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: umysql_vc
       WORDPRESS_DB_PASSWORD: 555gpah4jzetczpf
       WORDPRESS_DB_NAME: vc_wp_codesnippets
       WORDPRESS_TABLE_PREFIX: 'vc_wp_'
     networks:
      - app-network

volumes:
    db:

networks:
  app-network: